sudo: required
dist: trusty
language: php

# Versi php
php:
  - '7.2'

# Brance yang digunakan
branches:
  only:
    - master # QA/Staging server
    - development # DevServer

services:
  - docker

# install Environment di OS
before_install:
  - composer install
  - cp .env.excample .env
  - php artisan key:generate

# Precompile
before_script:
  - 

# Main Execution (Build)
script:
  - vendor/bin/phpunit
